# Generated by Django 3.1.5 on 2023-01-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('diseaseid', models.CharField(db_column='DiseaseID', max_length=10, primary_key=True, serialize=False)),
                ('diseasename', models.CharField(blank=True, db_column='DiseaseName', max_length=255, null=True)),
                ('omimid', models.CharField(blank=True, db_column='OmimID', max_length=10, null=True)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('geneid', models.CharField(db_column='GeneID', max_length=10, primary_key=True, serialize=False)),
                ('genename', models.CharField(blank=True, db_column='GeneName', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=50, null=True)),
                ('details', models.CharField(blank=True, db_column='Details', max_length=100, null=True)),
            ],
            options={
                'db_table': 'gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('diseasename', models.CharField(db_column='DiseaseName', max_length=50, primary_key=True, serialize=False)),
                ('maplink', models.CharField(blank=True, db_column='MapLink', max_length=255, null=True)),
                ('mapid', models.CharField(blank=True, db_column='MapID', max_length=255, null=True)),
                ('mapimage', models.CharField(blank=True, db_column='MapImage', max_length=255, null=True)),
            ],
            options={
                'db_table': 'map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolism',
            fields=[
                ('metabolismid', models.CharField(db_column='MetabolismID', max_length=50, primary_key=True, serialize=False)),
                ('metabolismname', models.CharField(blank=True, db_column='MetabolismName', max_length=50, null=True)),
                ('chemicalformula', models.CharField(blank=True, db_column='ChemicalFormula', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('reference', models.CharField(blank=True, db_column='Reference', max_length=250, null=True)),
                ('details', models.CharField(db_column='Details', max_length=100)),
            ],
            options={
                'db_table': 'metabolism',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('diseaseid', models.OneToOneField(db_column='DiseaseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DiseaseModel.disease')),
                ('phenotype', models.CharField(blank=True, db_column='Phenotype', max_length=255, null=True)),
            ],
            options={
                'db_table': 'effect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('metabolismid', models.OneToOneField(db_column='MetabolismID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DiseaseModel.metabolism')),
                ('omimid', models.CharField(db_column='OmimID', max_length=255)),
            ],
            options={
                'db_table': 'process',
                'managed': False,
            },
        ),
    ]
